# Bash Script Project Template
# Source: https://github.com/panubo/reference-github-actions/blob/main/pre-commit-configs/bash.pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable

-   repo: https://github.com/panubo/pre-commit-hooks
    rev: v0.2.1
    hooks:
    -   id: shellcheck
